version: '3'

services:
  app:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - discovery

  webform:
    build: ./webform
    ports:
      - "5000:5000"

  discovery:
    build: ./discovery
    ports:
      - "6000:6000"

  extension:
    build: ./extension
